filebeat-1:
  image: docker.elastic.co/beats/filebeat:6.8.7
  container_name: filebeat-1
  network_mode: host
  volumes:
    - /var/log/capture:/var/log/capture
    - /opt/filebeat/conf/filebeat.yaml:/usr/share/filebeat/filebeat.yml
    - /opt/filebeat/conf/etc/registry:/usr/share/filebeat/data
  user: root
  restart: always
